<script>
  // export let eventTicket;
  export let membership;

  import { navigateTo, router } from 'yrv';
  import { getContext } from 'svelte';

  import config from '../../../../config';
  import { login } from '../../../../utilities/security';
  import Notices from '../_Notices.svelte';

  import { Check, Ban } from '../../../../elements/svgs';
  import {
    Standard as StandardButton,
    Highlight as HighlightButton,
  } from '../../../../elements/buttons';

  import { Standard as StandardLink } from '../../../../elements/links';

  const { id, name } = $router.params;
  const eventSlug = `${id}/${name}`;

  const { send } = getContext('cart');

  function handleAddMembershipClick(quantity = 1) {
    const isBulkPurchase = quantity > 1 ? true : false;
    send('ADD_ITEM', {
      eventId: config.eventId,
      ...membership,
      isBulkPurchase,
      quantity,
    });
    navigateTo('/orders/summary');
  }

  function handleAddEventTicketClick(quantity = 1) {
    // const isBulkPurchase = quantity > 1 ? true : false;
    // send('ADD_ITEM', { ...eventTicket, isBulkPurchase, quantity });
    // navigateTo('/orders/summary');
    navigateTo('/events');
  }
</script>

<div>
  <div class="bg-thatBlue-800 pt-12 px-4 sm:px-6 lg:px-8 lg:pt-20">
    <div class="relative flex flex-col items-center justify-center space-y-12">
      <p class="text-3xl font-extrabold text-white sm:text-4xl lg:text-5xl">
        Camper Tickets
      </p>

      <p
        class="text-center max-w-6xl mx-auto text-xl text-gray-300 sm:mt-5 sm:text-2xl">
        As a Camper you receive up to 4 days of 200 professional sessions across
        a wide range of technologies, platforms and disciplines of all levels.
        You can also access over 10,000 sq. ft. of open spaces to participate in
        more intimate discussions across all topics generated by you and your
        fellow attendees. All sessions including open spaces are designed to
        allow you to build your own track to level up your skills, career and
        take charge of YOU.
      </p>

      <div class="mt-8">
        <div class="flex flex-col">
          <StandardLink href="{`/events/${eventSlug}/tickets`}"
            >VIEW ALL TICKET OPTIONS</StandardLink>
        </div>
      </div>
    </div>
  </div>

  <div class="pb-6 lg:pb-10 bg-thatBlue-100 bg-opacity-25">
    <div class="bg-gradient-to-b from-thatBlue-800">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="pt-20 relative lg:grid lg:grid-cols-7">
          <div
            class="mx-auto max-w-md lg:mx-0 lg:max-w-none lg:col-start-1 lg:col-end-3 lg:row-start-2 lg:row-end-3">
            <div
              class="h-full flex flex-col rounded-lg shadow-lg overflow-hidden lg:rounded-none lg:rounded-l-lg">
              <div class="flex-1 flex flex-col">
                <div class="bg-white px-6 py-10">
                  <div>
                    <h3
                      class="text-center text-2xl font-bold uppercase text-gray-500">
                      Pre-Conference
                    </h3>
                    <div class="mt-4 flex items-center justify-center">
                      <span
                        class="px-3 flex items-start text-6xl tracking-tight text-gray-900">
                        <span class="mt-2 mr-2 text-4xl font-medium"> $ </span>
                        <span class="font-extrabold"> 99 </span>
                      </span>
                    </div>
                  </div>
                </div>
                <div
                  class="flex-1 flex flex-col justify-between border-t-2 border-gray-100 p-6 bg-gray-50 sm:p-10 lg:p-6 xl:p-10">
                  <ul class="space-y-4">
                    <li class="flex items-start">
                      <div class="flex-shrink-0">
                        <Check />
                      </div>
                      <p class="ml-3 text-base font-medium text-gray-500">
                        Full Access to Event
                      </p>
                    </li>

                    <li class="flex items-start">
                      <div class="flex-shrink-0">
                        <Check />
                      </div>
                      <p class="ml-3 text-base font-medium text-gray-500">
                        Join any Session
                      </p>
                    </li>

                    <li class="flex items-start">
                      <div class="flex-shrink-0">
                        <Check />
                      </div>
                      <p class="ml-3 text-base font-medium text-gray-500">
                        Create any Session
                      </p>
                    </li>
                  </ul>
                  <div class="mt-8">
                    <div class="flex flex-col">
                      <StandardButton
                        on:click="{() => handleAddEventTicketClick()}">
                        Purchase
                      </StandardButton>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            class="mt-10 max-w-lg mx-auto lg:mt-0 lg:max-w-none lg:mx-0 lg:col-start-3 lg:col-end-6 lg:row-start-1 lg:row-end-4">
            <div class="relative rounded-lg shadow-xl">
              <div
                class="pointer-events-none absolute inset-0 rounded-lg border-2 border-thatOrange-400"
                aria-hidden="true">
              </div>
              <div class="absolute inset-x-0 top-0 transform translate-y-px">
                <div class="flex justify-center transform -translate-y-1/2">
                  <span
                    class="inline-flex rounded-full bg-thatOrange-400 px-4 py-1 text-sm font-bold tracking-wider uppercase text-white">
                    Best Value
                  </span>
                </div>
              </div>
              <div class="bg-white rounded-t-lg px-6 pt-12 pb-10">
                <div>
                  <h3
                    class="text-center text-2xl font-bold uppercase text-gray-500">
                    THAT Everything
                  </h3>
                  <div class="mt-4 flex items-center justify-center">
                    <span
                      class="px-3 flex items-start text-6xl tracking-tight text-gray-900">
                      <span class="mt-2 mr-2 text-4xl font-medium"> $ </span>
                      <span class="font-extrabold">
                        {membership?.price || 749}
                      </span>
                    </span>
                  </div>
                </div>
              </div>
              <div
                class="border-t-2 border-gray-100 rounded-b-lg pt-10 pb-8 px-6 bg-gray-50 sm:px-10 sm:py-10">
                <ul class="space-y-4">
                  <li class="flex items-start">
                    <div class="flex-shrink-0">
                      <Check />
                    </div>
                    <p class="ml-3 text-base font-medium text-gray-500">
                      Access to all online monthly events
                    </p>
                  </li>

                  <li class="flex items-start">
                    <div class="flex-shrink-0">
                      <Check />
                    </div>
                    <p class="ml-3 text-base font-medium text-gray-500">
                      $50 off 1 THAT Conference Camper Ticket
                    </p>
                  </li>

                  <li class="flex items-start">
                    <div class="flex-shrink-0">
                      <Check />
                    </div>
                    <p class="ml-3 text-base font-medium text-gray-500">
                      10% off at THAT Store
                    </p>
                  </li>
                  <li class="flex items-start">
                    <div class="flex-shrink-0">
                      <Check />
                    </div>
                    <p class="ml-3 text-base font-medium text-gray-500">
                      Yearly Commitment, Automatic Renewal
                    </p>
                  </li>
                  <li class="flex items-start">
                    <div class="flex-shrink-0">
                      <Check />
                    </div>
                    <p class="ml-3 text-base font-medium text-gray-500">
                      First access to new platform features
                    </p>
                  </li>
                </ul>
                <div class="mt-10">
                  <div class="flex flex-col">
                    <HighlightButton
                      on:click="{() => handleAddMembershipClick()}">
                      Purchase
                    </HighlightButton>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            class="mt-10 mx-auto max-w-md lg:m-0 lg:max-w-none lg:col-start-6 lg:col-end-8 lg:row-start-2 lg:row-end-3">
            <div
              class="h-full flex flex-col rounded-lg shadow-lg overflow-hidden lg:rounded-none lg:rounded-r-lg">
              <div class="flex-1 flex flex-col">
                <div class="bg-white px-6 py-10">
                  <div>
                    <h3
                      class="text-center text-2xl font-bold uppercase text-gray-500">
                      Online Only
                    </h3>
                    <div class="mt-4 flex items-center justify-center">
                      <span
                        class="px-3 flex items-start text-6xl tracking-tight text-gray-900">
                        <span class="mt-2 mr-2 text-4xl font-medium"> $ </span>
                        <span class="font-extrabold"> 149 </span>
                      </span>
                    </div>
                  </div>
                </div>
                <div
                  class="flex-1 flex flex-col justify-between border-t-2 border-gray-100 p-6 bg-gray-50 sm:p-10 lg:p-6 xl:p-10">
                  <ul class="space-y-4">
                    <li class="flex items-start">
                      <div class="flex-shrink-0">
                        <Check />
                      </div>
                      <p class="ml-3 text-base font-medium text-gray-500">
                        Join Activities
                      </p>
                    </li>

                    <li class="flex items-start">
                      <div class="flex-shrink-0">
                        <Check />
                      </div>
                      <p class="ml-3 text-base font-medium text-gray-500">
                        Create Activities
                      </p>
                    </li>

                    <li class="flex items-start">
                      <div class="flex-shrink-0">
                        <Ban />
                      </div>
                      <p class="ml-3 text-base font-medium text-gray-500">
                        Access to monthly events
                      </p>
                    </li>
                  </ul>
                  <div class="mt-8">
                    <div class="flex flex-col">
                      <StandardButton
                        on:click="{() => login('/my/settings/profile', true)}">
                        Purchase
                      </StandardButton>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <Notices />
  </div>
</div>
